Zuul: test deployment job
packit/deployment pull request #147
Opened 2020-10-07 11:57 UTC by jpopelka

2020-10-08 09:21 UTC, TomasTomecek requested changes
otherwise LGTM, nicely done

2020-10-08 09:21 UTC, TomasTomecek commented on .zuul.yaml
> +    name: test
names are global, so please make it more unique, something like `deployment-tests`

2020-10-09 06:42 UTC, jpopelka commented on .zuul.yaml
> +    name: test
I never remember that, thanks.

2020-10-09 12:07 UTC, TomasTomecek approved these changes
LGTM

did Lentilka help you?

2020-10-09 12:11 UTC, jpopelka commented
:dog: Yes, she did, but it was expensive :candy: :candy:  :candy: :meat_on_bone: :cut_of_meat:

2020-10-09 12:13 UTC, merged