WIP: Add splunk-fluentd-hec sidecar
packit/deployment pull request #352
Opened 2022-06-22 11:02 UTC by jpopelka

2022-10-06 07:37 UTC, jpopelka commented
Ready for review, it's been running in stg since yesterday.

2022-10-07 11:39 UTC, TomasTomecek requested changes
Even though I think I know what this change does, I'd appreciate a brief explanation in a README: explain what fluentd is, why we use it, what it does in our deployment, how & where are the logs stored; thanks!

Implementation LGTM

2022-10-11 17:43 UTC, jpopelka commented
> I'd appreciate a brief explanation in a README

Added [docs/logs.md](https://github.com/packit/deployment/blob/f011d68f8b1972303362dacc117abef3e010a64a/docs/logs.md)

2022-10-17 10:46 UTC, TomasTomecek approved these changes
👋👋👋

very nice write-up, thank you!

2022-10-18 08:15 UTC, merged